### ISSUE TITLE
why do..while?

### ISSUE THREAD

**Issue by Nartynka** [Ania000/Wozny#4]
You can use normal while
https://github.com/Ania000/Wozny/blob/9f096e1216139b0371fb1d56d574a4260a3ee4f9/Wozny/Iohandler.cpp#L10
https://github.com/Ania000/Wozny/blob/9f096e1216139b0371fb1d56d574a4260a3ee4f9/Wozny/Notepad.cpp#L43
https://github.com/Ania000/Wozny/blob/9f096e1216139b0371fb1d56d574a4260a3ee4f9/Wozny/Wozny.cpp#L18

**Comment by Ania000** [comment]
In one place it was actually necessary
